// src/utils/numberGenerator.ts
import { Connection } from "typeorm";

// Simpleng class helper base sa code mo
class AutoGeneratedNumberCls {
  autoGeneratedNo: string = "";
}

export const generateAutoNumber = async (autoNoType: string, connection: any): Promise<string | null> => {
  try {
    // Tawagin ang MySQL Function
    let autoNum = await connection.manager.query("SELECT setAuto_number(?) as an", [autoNoType]);

    if (autoNum && autoNum.length > 0) {
      // Kunin ang 'an' property mula sa unang row ng result
      let anStr: string = autoNum[0].an; 

      let yearNow = new Date().getFullYear();
      let agnSplit = anStr.split("|");
      let agnYear = String(yearNow).substring(2);
      
      // Logic para sa pag-combine (Prefix + Year + Sequence)
      let autoGeneratedNo = agnSplit[0] + (!['', null, undefined].includes(agnSplit[1]) ? agnYear : '') + agnSplit[2];

      return autoGeneratedNo;
    } else {
      return null;
    }
  } catch (error) {
    console.error("AutoNumber Error:", error);
    throw error;
  }
};